<?php

namespace app\controllers;

use app\models\Category;
use app\models\Medicine;
use app\models\MedicineCategory;
use sizeg\jwt\JwtHttpBearerAuth;
use Yii;
use yii\db\Query;
use yii\filters\auth\CompositeAuth;
use yii\filters\auth\HttpBearerAuth;
use yii\filters\auth\QueryParamAuth;
use yii\filters\Cors;

class CategoryController extends \yii\web\Controller
{
    public $enableCsrfValidation = false;

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'api-docs' => [
                'class' => 'genxoft\swagger\ViewAction',
                'apiJsonUrl' => \yii\helpers\Url::to(['/site/api-json'], true),
            ],
            'api-json' => [
                'class' => 'genxoft\swagger\JsonAction',
                'dirs' => [
                    Yii::getAlias('@app/controllers'),
                    Yii::getAlias('@app/models'),
                ],
            ],
        ];
    }

    public function behaviors()
    {
        $behaviors = parent::behaviors(); // TODO: Change the autogenerated stub
        $behaviors['corsFilter'] = [
            'class' => Cors::class,
            'cors' => [
                'Origin' => Yii::$app->params['allowedDomains'],
                'Access-Control-Request-Method' => ['*'],
                'Access-Control-Allow-Methods' => ['POST', 'PUT', 'OPTIONS', 'GET'],
                'Access-Control-Allow-Headers' => ['*'],
                'Access-Control-Request-Headers' => ['*'],
                'Access-Control-Allow-Credentials' => true,
            ]
        ];
        $behaviors['authenticator'] = [
            'class' => CompositeAuth::class,
            'authMethods' => [
                HttpBearerAuth::class,
                QueryParamAuth::class,
                JwtHttpBearerAuth::class
            ]
        ];
        return $behaviors;
    }

    public function beforeAction($action)
    {
        Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        return parent::beforeAction($action);
    }

    public function actionIndex()
    {
        return ['status' => 'ok', 'msg' => 'It\'s working'];
    }

    public function actionAdd()
    {
        try {
            $errors = [
                'notExist' => [],
                'categoryErrors' => [],
                'used' => [],
            ];


            $data = json_decode(Yii::$app->request->getRawBody(), true);
            if (!isset($data['categories'])) {
                return ["status" => "error", "details" => "There are missing params (categories)"];
            }

            if (!isset($data['deletedCategories'])) {
                return ["status" => "error", "details" => "There are missing params (deletedCategories)"];
            }

            if (!empty($data['deletedCategories'])) {
                foreach ($data['deletedCategories'] as $id) {
                    $category = Category::findOne(['id' => (int)$id]);
                    if ($category !== null && MedicineCategory::findOne(['categoryId' => (int)$id]) === null) {
                        MedicineCategory::deleteAll(['categoryId' => (int)$id]);

                        $category->delete();
                    } else {
                        if ($category) {
                            $errors['used'][] = ["Category that has this name $category->name is used"];
                        } else {
                            $errors['notExist'][] = ["Category that has this id $id is not exist"];
                        }
                    }
                }
            }

            foreach ($data['categories'] as $category) {
                $category = (array)$category;
                if ($category['id'] === '') {
                    $newCategory = new Category();
                } else {
                    $newCategory = Category::findOne(['id' => (int)$category['id']]);
                    if ($newCategory === null) {
                        $errors['notExist'][] = ["Category that has this id " . $category['id'] . " is not exist"];
                        continue;
                    }
                }
                $newCategory->name = trim($category['name']);
                if ($newCategory->validate()) {
                    $newCategory->save();
                } else {
                    $errors['categoryErrors'][] = $newCategory->getErrors();
                }
            }
            return ['status' => 'ok', 'errors' => $errors];
        } catch (\Exception $e) {
            return ['msg' => 'error', 'details' => $e->getMessage()];
        }
    }

    public function actionGetAll()
    {
        $categories = Category::find()->where([])->asArray()->all();
        return ['status' => 'status', 'categories' => $categories];
    }

    function actionGet($id)
    {
        $category = Category::find()->where(['id' => (int)$id])->one();
        if ($category === null)
            return ["status" => "error", "details" => "There is no category"];

        return ['status' => 'ok', 'category' => $category];
    }

    function actionGetMedicines($categoryId)
    {
        try {
            $medicines = (new Query())
                ->select([
                    "productName",
                    "indications",
                    "barcode",
                    "composition",
                    "packing",
                    "expiredDate",
                    "price",
                    "netPrice",
                    "name as categoryName"
                ])
                ->from('medicine_category')
                ->innerJoin('medicine', 'medicine.id=medicine_category.medicineId')
                ->innerJoin('category', 'category.id=medicine_category.categoryId')
                ->where(['category.id' => $categoryId])
                ->all();

            if (empty($medicines))
                return ['status' => 'error', 'details' => "There are no medicine that has this category id ($categoryId)"];

            return ['status' => 'ok', 'medicines' => $medicines];
        } catch (\Exception $e) {
            return ['msg' => 'error', 'details' => $e->getMessage()];
        }
    }
}
