<?php

namespace app\controllers;

use app\models\Offer;
use app\models\OfferDetails;
use app\models\Order;
use app\models\OrderDetails;
use app\models\User;
use sizeg\jwt\JwtHttpBearerAuth;
use Yii;
use yii\db\Query;
use yii\filters\auth\CompositeAuth;
use yii\filters\auth\HttpBearerAuth;
use yii\filters\auth\QueryParamAuth;
use yii\filters\Cors;
use yii\helpers\Url;
use yii\web\Controller;

class OrderController extends Controller
{

    public $enableCsrfValidation = false;

    public function behaviors()
    {
        $behaviors = parent::behaviors(); // TODO: Change the autogenerated stub
        $behaviors['corsFilter'] = [
            'class' => Cors::class,
            'cors' => [
                'Origin' => Yii::$app->params['allowedDomains'],
                'Access-Control-Request-Method' => ['*'],
                'Access-Control-Allow-Methods' => ['POST', 'PUT', 'OPTIONS', 'GET'],
                'Access-Control-Allow-Headers' => ['*'],
                'Access-Control-Request-Headers' => ['*'],
                'Access-Control-Allow-Credentials' => true,
            ]
        ];
        $behaviors['authenticator'] = [
            'class' => CompositeAuth::class,
            'authMethods' => [
                HttpBearerAuth::class,
                QueryParamAuth::class,
                JwtHttpBearerAuth::class
            ]
        ];
        return $behaviors;
    }

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'api-docs' => [
                'class' => 'genxoft\swagger\ViewAction',
                'apiJsonUrl' => \yii\helpers\Url::to(['/site/api-json'], true),
            ],
            'api-json' => [
                'class' => 'genxoft\swagger\JsonAction',
                'dirs' => [
                    Yii::getAlias('@app/controllers'),
                    Yii::getAlias('@app/models'),
                ],
            ],
        ];
    }

    public function beforeAction($action)
    {
        Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        return parent::beforeAction($action);
    }

    public function actionIndex()
    {
        return ['status' => 'ok', 'status' => 'working'];
    }

    function actionAdd()
    {
        try {
            $errors = [];
            $data = (array)json_decode(Yii::$app->request->getRawBody());
            if (!isset($data['userId']) || !isset($data['representativeId']) || !isset($data['orderDetails']))
                return ['status' => 'error', 'details' => 'There are missing params (userId or representativeId or orderDetails)'];

            $orderDetails = $data['orderDetails'];
            if (empty($orderDetails))
                return ['status' => 'error', 'details' => 'Order details should not be empty'];

            if ((int)$data['representativeId'] === (int)$data['userId'])
                return ['status' => 'error', 'details' => 'User id should not be the same as Representative id'];

            $newOrder = new Order();
            $newOrder->userId = (int)$data['userId'];
            $newOrder->representativeId = (int)$data['representativeId'];
            $newOrder->orderDate = date('Y-m-d H:i:s');
            $newOrder->isCanceled = 0;
            $newOrder->isCompleted = 0;
            if ($newOrder->validate()) {
                $newOrder->save();
                foreach ($orderDetails as $o) {
                    $o = (array)$o;
                    $newOrderDetails = new OrderDetails();
                    $newOrderDetails->orderId = $newOrder->id;
                    $newOrderDetails->offerId = (int)$o['offerId'];
                    $newOrderDetails->quantity = (int)$o['quantity'];
                    if ($newOrderDetails->validate()) {
                        $newOrderDetails->save();
                    } else {
                        $errors[] = $newOrderDetails->getErrors();
                    }
                }
                return ['status' => 'ok', 'errors' => $errors];
            } else {
                return ['status' => 'error', 'details' => $newOrder->getErrors()];
            }
        } catch (\Exception $e) {
            return ['status' => 'error', 'details' => $e->getMessage()];
        }
    }

    function actionCompleted($id)
    {
        try {
            $order = Order::findOne(['id' => (int)$id]);
            if ($order === null)
                return ['status' => 'error', 'details' => 'There is no order that has this id'];

            if ($order->isCompleted === 1)
                return ['status' => 'error', 'details' => 'The order is already completed'];

            $order->isCompleted = 1;
            if ($order->validate() && $order->save()) {
                return ['status' => 'ok'];
            } else {
                return ['status' => 'error', 'details' => $order->getErrors()];
            }
        } catch (\Exception $e) {
            return ['status' => 'error', 'details' => $e->getMessage()];
        }
    }

    function actionCanceled($id)
    {
        try {
            $order = Order::findOne(['id' => (int)$id]);
            if ($order === null)
                return ['status' => 'error', 'details' => 'There is no order that has this id'];

            if ($order->isCanceled === 1)
                return ['status' => 'error', 'details' => 'The order is already canceled'];

            $order->isCanceled = 1;
            if ($order->validate() && $order->save()) {
                return ['status' => 'ok'];
            } else {
                return ['status' => 'error', 'details' => $order->getErrors()];
            }
        } catch (\Exception $e) {
            return ['status' => 'error', 'details' => $e->getMessage()];
        }
    }

    function actionGetAll($year = null, $month = null)
    {
        try {
            if (Yii::$app->user->identity->role === 5) {
                $orders = Order::find()->where([]);
            } else {
                $orders = Order::find()->where(['userId' => Yii::$app->user->identity->id]);
            }

            if ($year != null && $month != null) {
                $month = str_pad($month, 2, '0', STR_PAD_LEFT);
                $endDayMonth = date('t', strtotime("$year-$month-01"));
                $orders->andFilterWhere(['between', 'orderDate', date('Y-m-d H:i:s', strtotime("$year-$month-01")), date('Y-m-d H:i:s', strtotime("$year-$month-$endDayMonth"))]);
            }

            $orders = $orders->with('representative', 'user')->asArray()->all();
            if ($orders) {
                return ['status' => 'ok', 'orders' => $orders];
            } else {
                return ['status' => 'error', 'details' => 'There is no order'];
            }
        } catch (\Exception $e) {
            return ['status' => 'error', 'details' => $e->getMessage()];
        }
    }
    function actionGetAllCanceled($isCanceled = 0, $year = null, $month = null)
    {
        try {
            $orders = Order::find();
            if (Yii::$app->user->identity->role === 5) {
                $orders = Order::find()->where(['isCanceled' => (int)$isCanceled]);
            } else {
                $orders = Order::find()->where(['isCanceled' => (int)$isCanceled, 'userId' => Yii::$app->user->identity->id]);
            }

            if ($year != null && $month != null) {
                $month = str_pad($month, 2, '0', STR_PAD_LEFT);
                $endDayMonth = date('t', strtotime("$year-$month-01"));
                $orders->andFilterWhere(['between', 'orderDate', date('Y-m-d H:i:s', strtotime("$year-$month-01")), date('Y-m-d H:i:s', strtotime("$year-$month-$endDayMonth"))]);
            }

            $orders =$orders
                ->with('representative', 'user')
                ->asArray()
                ->all();

            if ($orders) {
                return ['status' => 'ok', 'orders' => $orders];
            } else {
                return ['status' => 'error', 'details' => 'There is no order'];
            }
        } catch (\Exception $e) {
            return ['status' => 'error', 'details' => $e->getMessage()];
        }
    }

    function actionGetAllCompleted($isCompleted = 0, $year = null, $month = null)
    {
        try {
            if (Yii::$app->user->identity->role === 5) {
                $orders = Order::find()->where(['isCompleted' => (int)$isCompleted]);
            } else {
                $orders = Order::find()->where(['isCompleted' => (int)$isCompleted, 'userId' => Yii::$app->user->identity->id]);
            }

            if ($year != null && $month != null) {
                $month = str_pad($month, 2, '0', STR_PAD_LEFT);
                $endDayMonth = date('t', strtotime("$year-$month-01"));
                $orders->andFilterWhere(['between', 'orderDate', date('Y-m-d H:i:s', strtotime("$year-$month-01")), date('Y-m-d H:i:s', strtotime("$year-$month-$endDayMonth"))]);
            }

            $orders = $orders->with('representative', 'user')->asArray()->all();
            if ($orders) {
                return ['status' => 'ok', 'orders' => $orders];
            } else {
                return ['status' => 'error', 'details' => 'There is no order'];
            }
        } catch (\Exception $e) {
            return ['status' => 'error', 'details' => $e->getMessage()];
        }
    }

    public function actionDeleteOffer()
    {
        try {
            $data = (array)json_decode(Yii::$app->request->getRawBody());
            if (!isset($data['id']))
                return ['status' => 'error', 'details' => 'There are missing param'];

            $id = (int)$data['id'];
            $orderDetails = OrderDetails::findOne(['offerId' => $id]);
            if ($orderDetails === null)
                return ['status' => 'error', 'details' => 'There is no offer in this order'];

            if (Order::findOne(['id' => $orderDetails->orderId, 'isCompleted' => 1]) !== null)
                return ['status' => 'error', 'details' => 'You can not delete an offer from this order'];

            if ($orderDetails->delete()) {
                return ['status' => 'ok'];
            } else {
                return ['status' => 'error', 'details' => $orderDetails->getErrors()];
            }
        } catch (\Exception $e) {
            return ['status' => 'error', 'details' => $e->getMessage()];
        }
    }


    function actionGet($id)
    {
        try {
            $order = Order::find()->where(['id' => (int)$id])->with('representative', 'user', 'offers', 'orderDetails')->asArray()->one();

            if ($order === null)
                return ['status' => 'error', 'details' => 'There is no order that has this id'];

            $offers = [];

            foreach ($order['offers'] as $key => $offer) {
                $offer  = Offer::find()->where(['id' => $offer['id']])
                    ->with('medicines', 'extraMedicines')
                    ->asArray()
                    ->one();
                $offer['quantity'] = $order['orderDetails'][$key]['quantity'];
                $offers[] = $offer;
            }
            $order['offers'] = $offers;
            unset($order['orderDetails']);

            return ['status' => 'ok', 'order' => $order];
        } catch (\Exception $e) {
            return ['status' => 'error', 'details' => $e->getMessage()];
        }
    }
}
